CUDA_VISIBLE_DEVICES=0 python test.py \
    --test_dataset "../../collection_photo" \
    --tgt_dataset "../data_art_backup" \
    --tgt_img_size 256 \
    --tgt_crop_size 256 \
    --workers 1 \
    --feature_dim 156160 \
    --gamma_dim 256 \
    --beta_dim 256 \
    --omega_dim 4 \
    --encoder_out_ch 128 \
    --db_number 4 \
    --ws 64 \
    --M 2 \
    --sample_dir "results_DRB_GAN" \
    --pretrain_model "train_log/checkpoint_DRB_GAN/DRBGAN_it_500000.pt" \
    --mixture_list "paul-cezanne" "monet" \
    --mixture_weights 0.5 0.5
