mkdir 'log_DRB_GAN_animal'
CUDA_VISIBLE_DEVICES=0 python train.py \
    --src_dataset "../../Animal_dataset/train" \
    --tgt_dataset "../data_art_backup" \
    --test_dataset "../../Animal_dataset/val" \
    --iter 600000 \
    --batch_size 1 \
    --training_rate 1 \
    --img_size 512 \
    --crop_size 512 \
    --workers 1 \
    --print_freq 5000 \
    --save_freq 100000 \
    --g_lr 0.0001 \
    --d_lr 0.0001 \
    --feature_dim 639488 \
    --gamma_dim 200 \
    --beta_dim 200 \
    --omega_dim 4 \
    --encoder_out_ch 128 \
    --db_number 4 \
    --ws 128 \
    --M 2 \
    --g_adv_weight 1.5 \
    --d_adv_weight 1.5 \
    --con_weight 1.0 \
    --sty_weight 0.05 \
    --perceptual_weight 1. \
    --class_weight 1. \
    --gan_loss "nsgan" \
    --checkpoint_dir "checkpoint_DRB_GAN_animal" \
    --log_dir "log_DRB_GAN_animal" \
    --sample_dir "samples_DRB_GAN_animal" \
2>&1 | tee log_DRB_GAN_animal/log.log
