mkdir 'log_DRB_GAN'
CUDA_VISIBLE_DEVICES=0 python train.py \
    --src_dataset "../Photo_image_training_data" \
    --tgt_dataset "../data_art_backup" \
    --test_dataset "../photo2fourcollection-20210312T150938Z-001/photo2fourcollection/testA" \
    --iter 600000 \
    --batch_size 1 \
    --training_rate 1 \
    --img_size 256 \
    --crop_size 256 \
    --workers 1 \
    --print_freq 5000 \
    --save_freq 100000 \
    --g_lr 0.0001 \
    --d_lr 0.0001 \
    --feature_dim 156160 \
    --gamma_dim 256 \
    --beta_dim 256 \
    --omega_dim 4 \
    --encoder_out_ch 128 \
    --db_number 4 \
    --ws 64 \
    --M 2 \
    --g_adv_weight 1.5 \
    --d_adv_weight 1.5 \
    --con_weight 1.0 \
    --sty_weight 0.05 \
    --perceptual_weight 1. \
    --class_weight 1. \
    --gan_loss "nsgan" \
    --checkpoint_dir "checkpoint_DRB_GAN" \
    --log_dir "log_DRB_GAN" \
    --sample_dir "samples_DRB_GAN" \
2>&1 | tee log_DRB_GAN/log.log
