mkdir 'log_DRB_GAN_animal_style_data_v2'
CUDA_VISIBLE_DEVICES=1 python train.py \
    --src_dataset "../../Animal_dataset/train" \
    --tgt_dataset "../art_dataset_v2" \
    --test_dataset "../../Animal_dataset/val" \
    --iter 700000 \
    --batch_size 1 \
    --training_rate 1 \
    --img_size 512 \
    --crop_size 512 \
    --workers 1 \
    --print_freq 5000 \
    --save_freq 100000 \
    --g_lr 0.0001 \
    --d_lr 0.0001 \
    --feature_dim 655360 \
    --gamma_dim 128 \
    --beta_dim 128 \
    --omega_dim 4 \
    --encoder_out_ch 128 \
    --db_number 4 \
    --ws 128 \
    --M 2 \
    --g_adv_weight 1.0 \
    --d_adv_weight 1.0 \
    --con_weight 1.0 \
    --sty_weight 0.05 \
    --perceptual_weight 1. \
    --class_weight 1. \
    --gan_loss "nsgan" \
    --checkpoint_dir "checkpoint_DRB_GAN_animal_style_data_v2" \
    --log_dir "log_DRB_GAN_animal_style_data_v2" \
    --sample_dir "samples_DRB_GAN_animal_style_data_v2"

